scope: postgres-cluster
namespace: /db/
name: ${PATRONI_NAME}

restapi:
  listen: ${PATRONI_RESTAPI_LISTEN}
  connect_address: ${PATRONI_RESTAPI_CONNECT_ADDRESS}

etcd:
  host: ${PATRONI_ETCD_HOST}
  protocol_version: 3

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: 100
        shared_buffers: 256MB
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 100
      pg_hba:
        - local   all             all                                   trust
        - local   all             postgres                             trust
        - local   replication     all                                  trust
        - host    all             all             127.0.0.1/32        scram-sha-256
        - host    all             all             ::1/128             scram-sha-256
        - host    replication     replicator      all                 md5
        - host    all             all             all                 md5

  initdb:
    - encoding: UTF8
    - locale: C.UTF-8

postgresql:
  listen: ${PATRONI_POSTGRESQL_LISTEN}
  connect_address: ${PATRONI_POSTGRESQL_CONNECT_ADDRESS}
  data_dir: ${PATRONI_POSTGRESQL_DATA_DIR}
  pgpass: ${PATRONI_POSTGRESQL_PGPASS}
  authentication:
    replication:
      username: replicator
      password: ${PATRONI_POSTGRESQL_REPLICATION_PASSWORD}
    superuser:
      username: admin
      password: ${PATRONI_POSTGRESQL_ADMIN_PASSWORD}

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
