version: '3'

services:
  haproxy:
    image: haproxy:2.4
    container_name: emqx_haproxy
    ports:
      - "1883:1883"   # MQTT
      - "8083:8083"   # WebSocket
      - "8883:8883"   # MQTT TLS
      - "8084:8084"   # WebSocket TLS
      - "18083:18083" # Dashboard
      - "9090:9090"   # HAProxy Stats
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - emqx1
      - emqx2
      - emqx3
    networks:
      - emqx-net

  emqx1:
    image: emqx:5.1
    container_name: emqx1
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io]"
    networks:
      emqx-net:
        aliases:
          - node1.emqx.io

  emqx2:
    image: emqx:5.1
    container_name: emqx2
    environment:
      - "EMQX_NODE_NAME=emqx@node2.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io]"
    networks:
      emqx-net:
        aliases:
          - node2.emqx.io

  emqx3:
    image: emqx:5.1
    container_name: emqx3
    environment:
      - "EMQX_NODE_NAME=emqx@node3.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io,emqx@node3.emqx.io]"
    networks:
      emqx-net:
        aliases:
          - node3.emqx.io

networks:
  emqx-net:
    driver: bridge
